# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Next.js app to Azure Web App - babar2000

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js application
        run: npm run build
        env:
          # Add any build-time environment variables here
          NODE_ENV: production
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          # Add other environment variables your build process needs

      - name: Run tests (if available)
        run: npm run test --if-present
        continue-on-error: false

      # Only upload necessary files for deployment
      - name: Prepare deployment package
        run: |
          # Create deployment directory
          mkdir deployment-package
          
          # Copy necessary files for Next.js production
          cp -r .next deployment-package/
          cp -r public deployment-package/ 2>/dev/null || true
          cp package*.json deployment-package/
          cp next.config.* deployment-package/ 2>/dev/null || true
          
          # Copy any other necessary config files
          cp web.config deployment-package/ 2>/dev/null || true

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: deployment-package

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
          path: .
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'babar2000'
          slot-name: 'Production'
          package: .
          # Specify startup command for Next.js
          startup-command: 'npm start'